# Generated by Django 2.2.3 on 2019-07-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.PositiveIntegerField(max_length=13)),
                ('designation', models.CharField(max_length=50)),
                ('skills', models.TextField(max_length=500)),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
