# Generated by Django 2.2.3 on 2019-07-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0002_auto_20190702_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='about',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
