# Generated by Django 2.2.3 on 2019-07-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0003_employeedetails_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='about',
            field=models.TextField(max_length=500),
        ),
    ]
