# Generated by Django 2.2.3 on 2019-07-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeProfile', '0004_auto_20190703_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='mobile',
            field=models.CharField(max_length=13),
        ),
    ]
